### ISSUE TITLE
How to define REALLOC in OPLIST?

### ISSUE THREAD

**Issue by lindsaywhitney** [P-p-H-d/mlib#111]
How to define REALLOC in OPLIST?
There is error in following code:

 static data_node * data_node_realloc(data_node * obj, size_t size);

ARRAY_DEF(/* the array prefix */ array_data_node,
	  /* the object type */ data_node,
	  /* the object oplist */ (INIT(API_2(data_node_init)),
				   SET(API_6(data_node_set)),	 REALLOC(API(data_node_realloc,ARGPTR1,ARGPTR2,ARG3)),
				   INIT_SET(API_6(data_node_init_set)),
				   CLEAR(API_2(data_node_clear))))

**Comment by P-p-H-d** [comment]
Hi,

 You need to define it like this:

```
ARRAY_DEF(/* the array prefix */ array_data_node,
	  /* the object type */ data_node,
	  /* the object oplist */ (INIT(API_2(data_node_init)),
				   SET(API_6(data_node_set)),
				   REALLOC(API(data_node_realloc,NONE, ARG2, ARG3)),
				   INIT_SET(API_6(data_node_init_set)),
				   CLEAR(API_2(data_node_clear))))

```  
More information:
* ARG1 is the type itself, which is useless for your already strongly type function.
* It already expects the argument to be pointer to object, so no need to add an additional pointer.
* Since the prototype of the operator expects a pointer as return value, there is no transformation to perform to match your prototype.

Additional notes on this code which may be bugs:
* there is no INIT_SET operator (copy constructor), which is likely to be problematic for your object
* you over-define the REALLOC operator but not the FREE operator, which means standard C "free" function will be used. I am not sure it is want you want.
