### ISSUE TITLE
OPLIST for m-mutex.h elements

### ISSUE THREAD

**Issue by mario-tux** [P-p-H-d/mlib#36]
I understand that I'm trying to do OOP using C and m*lib containers as base (data + common methods). Maybe I'm going too far...

More or less with the same motivations on #34 , I need to embed an m_mutex_t and an m_cond_t into a tuple. I'm saying it is related because the buffer is indeed a data-structure plus some mutex/condition variables to provide its blocking/atomic features. Now I need a blocking/atomic behavior for a dictionary so I wanted to embed all the necessary (dictionary, mutex, condition variable) into a tuple. I'm stuck because the latter are intended to be used as global variables (like buffer until yesterday).

Tell me if I'm going to be cumbersome and/or if what I prospect has flaws.

**Comment by P-p-H-d** [comment]
I am seeing some issues for SET and INIT_SET?
What will be the specification of these operators for such type?

**Comment by diraimondo** [comment]
I see the semantic issue. On the practical scenarios I was thinking I never would need to copy such structures. Generalizing a condition variable doesn't got a state (expect than the list of blocked threads but it would be too complex to manage and not so useful); the mutex got a state and, forcing the concept, it could be copied. Again, just an exercise to force the semantic: not practical use.
Dummy SET and INIT_SET could be fine.

If you don't like the idea, maybe I can just define an OPLIST for m_mutex_t and m_cond_t just to make it works for me (hint?). I was just thinking that if you provide atomic/blocking structures like the m-buffer.h elements, how I could extend such properties to other data-structures. That's what I need.

**Comment by diraimondo** [comment]
Thinking about this: I don't really need the nestability of m*lib containers to group such kind of atomic/blocking objects. I can still get any kind of m*lib container and group it with the necessary mutex/cond to make it atomic/blocking by means of a plain structure. I will never copy/nest it.

Maybe there could be some kind of general approach to get atomicity on the operations on a container.  A general approach to the blocking mechanism looks more difficult.

Feel free to close this if don't see a more general feature for the m*lib framework.

**Comment by P-p-H-d** [comment]
I don't think providing the oplists for mutex or conditional variables is the right way. They cannot be copied. They are linked with the protected data: we cannot access the protected data method without using the lock. You will need to write all the access code yourself, and some of the operator (like _get) cannot be encapsulated without a change of the function prototype (we need to copy the data we get, as the data may be changed by another thread once we release the lock).

I'm currently thinking about the general approach and how to do it. I think an oplist based transformation may do the job (kind of if the container provided PUSH, I can provide a protected PUSH method). Some method will need some changes (like GET) as seen above. Some others may need to lock both arguments to work (to copy a container into another) which may result in deadlock if not done properly.

Doing so, I have analyzed the use of the operators in M*LIB (in order to uniformize their use) and performed an API incompatible change (!): \_remove for dict & B+Tree has been renamed into \_erase in order to differentiate properly with \_remove for Array & List that take incompatible arguments (I kept a compatibility layer, you'll get deprecated warnings about their usage).

**Comment by P-p-H-d** [comment]
I have committed the new module "m-protect.h" that create a new container that automatically add mutex lock on operations of the given containers.
Example:
```
ARRAY_DEF(array1, int)
PROTECT_DEF(parray1, array1_t, ARRAY_OPLIST(array1))

DICT_DEF2(dict1, int, int)
PROTECT_DEF(pdict1, dict1_t, DICT_OPLIST(dict1))
```
(If you have a better name for the module, feel free to propose).

Beware: I haven't fully tested it yet, not all operators are defined and its oplist is not defined so it cannot be chained.

**Comment by P-p-H-d** [comment]
By the way, I don't understand why you wanted a conditional variable for protected dictionary access?

**Comment by diraimondo** [comment]
I was speaking of conditional variable because I was thinking on a way to make insert/extract, push/pop operations blocking when necessary.
For the name: at the moment it provides only mutex locking so an alternative could be ATOMIC_DEF. It is in some way related to m-atomic.h, right?

**Comment by P-p-H-d** [comment]
Ok
Currently, there is no way for insert / push to be blocking as the container don't have a fixed maximum size (there is a planned change to support such feature through custom allocation, but it is not available yet).
So only _get, _erase & _pop can be blocking.

I don't want to add such container in m-atomic.h: this header shall define only what is defined by stdatomic.h. It only exists due to C++ and non C11 compilers.

**Comment by P-p-H-d** [comment]
I have renamed the header as m-concurrent.h and the macro as CONCURRENT_DEF.

blocking methods are available:
* bool name ## _get_blocking(base_type *p, concurrent_t out, key_t key, bool blocking);
* bool name ## _pop_blocking(base_type *p, concurrent_t out, bool blocking);
There is no blocking variant for _push & _set as explained before.

oplist & formal tests remain to be done.

Could you tell me if it answers your needs?

**Comment by P-p-H-d** [comment]
I'm glad it answers your needs!

Non concurrent container (circular) buffer already exist: you can use dual-push-list or deque for this. However, they need a specialize oplist to provide such interface properly. Their exported oplist provide a stack interface (PUSH=push_back and POP=pop_back), whereas they need a queue interface (PUSH=push_front and POP=pop_back). You can override the operator PUSH when using DEQUE_OPLIST in the meantime.

Note that the provided fixed size buffer (m-buffer) is likely to be faster than a concurrent of deque for communicating data.

Pretty much any container is supported by m-concurrent at the moment. I tested list, list-dual-push, array, deque, deque and tuple. Probably also dict_set, dict_oa, dict_store, b+tree, rbtree work fine (otherwise it is a bug).

**Comment by diraimondo** [comment]
> Non concurrent container (circular) buffer already exist: you can use dual-push-list or deque for this. However, they need a specialize oplist to provide such interface properly. Their exported oplist provide a stack interface (PUSH=push_back and POP=pop_back), whereas they need a queue interface (PUSH=push_front and POP=pop_back). You can override the operator PUSH when using DEQUE_OPLIST in the meantime.
> 
> Note that the provided fixed size buffer (m-buffer) is likely to be faster than a concurrent of deque for communicating data.

Yes, I know I could use the linked list to get an unlimited stack or queue data-structure but, as you suggest, this implies different level of efficiency.

I was thinking that now the buffer (and variants in m-buffer.h) is now a specific case of the, more general, approach to use an ordinary (read unsafe against concurrency) container and make it concurrency secure using the m-concurrent.h additional layer. I would be a unifying approach and you could deprecate the whole m-buffer.h.

**Comment by diraimondo** [comment]
I was looking at the code of _get_blocking method in m-concurrent.h: am I wrong or if blocking=false the code doesn't get anything...? The same for _get_blocking.

**Comment by P-p-H-d** [comment]
:( 
I have fixed this. Thanks for your report.

**Comment by diraimondo** [comment]
> oplist & formal tests remain to be done.

What do you mean with "oplist remain"? Should I expect a CONCURRENT_OPLIST macro so I can embed a concurrent container into another? If I understood your arguments on "SET/INIT_SET methods vs mutex/cond" it should not be possible/make-sense, right? In such case I will group several concurrent containers using an ordinary structure.

**Comment by P-p-H-d** [comment]
> What do you mean with "oplist remain"? Should I expect a CONCURRENT_OPLIST macro so I can embed a concurrent container into another? 

 Yes I plan to add a CONCURRENT_OPLIST macro.

> If I understood your arguments on "SET/INIT_SET methods vs mutex/cond" it should not be possible/make-sense, right? 

 What I mean is you cannot copy the lock without copying the protected data together. Once you have a proper container that handle both (like the concurrent one), you can copy all the container. The methods _init_set & _set are already written for container and these methods lock the mutex while copying the data and release them afterwards.

>Could I suggest to include the classical _get method too in a concurrent container so, If one is interested only in getting the mutual exclusive access (without any blocking behavior), it is sufficient to change the container definition (with the double _def macro) but it is not necessary to search/replace any _get(...) invocation with a _get_blocking(..., false) one?

I am not sure to understand what you want. 
The _get method has an issue for concurrent container: since this method returns a pointer to the internal data of the requested element within the container, this pointer may become invalid due to an update of the container in another thread (for example, if the array is reallocated). As such, I think that the _get method is not doable in a safe way for concurrent container. This explains the reason of having _get_copy & _get_blocking methods.

**Comment by diraimondo** [comment]
> The _get method has an issue for concurrent container: since this method returns a pointer to the internal data of the requested element within the container, this pointer may become invalid due to an update of the container in another thread (for example, if the array is reallocated). As such, I think that the _get method is not doable in a safe way for concurrent container. This explains the reason of having _get_copy & _get_blocking methods.

Ok, now it is clear.

**Comment by diraimondo** [comment]
Trying to replace non-concurrent variant of a dict with the new concurrent secure one: it looks that in the _set_at the last parameter is not defined as const (as in dict). The const makes sense here.

**Comment by diraimondo** [comment]
Is it a bug or I'm using the new CONCURRENT_OPLIST macro in a wrong way?
```
#include "m-concurrent.h"
#include "m-dict.h"
#include "m-string.h"
#include "m-tuple.h"

DICT_DEF2(string_pool, string_t, string_t)
#define STRING_POOL_OPLIST                                                     \
    DICT_OPLIST(string_pool, STRING_OPLIST, STRING_OPLIST)
#define M_OPL_string_pool_t() STRING_POOL_OPLIST

CONCURRENT_DEF(string_pool_ts, string_pool_t, STRING_POOL_OPLIST)
#define STRING_POOL_TS_OPLIST                                                  \
    CONCURRENT_OPLIST(string_pool_ts, STRING_POOL_OPLIST)
#define M_OPL_string_pool_ts_t() STRING_POOL_TS_OPLIST

int main() {
    M_LET(pool, string_pool_ts_t) {
        //
    }
}
```

```
$ gcc -I custom-libs/include test/test-mini.c
In file included from custom-libs/include/m-concurrent.h:28,
                 from test/test-mini.c:1:
test/test-mini.c: In function ‘main’:
custom-libs/include/m-core.h:661:52: error: pasting "M_TOBOOLI_" and "(" does not give a valid preprocessing token
 #define M_BOOL(x)                   M_RET_ARG2(M_C(M_TOBOOLI_, x), 1, useless)
                                                    ^~~~~~~~~~
custom-libs/include/m-core.h:107:29: note: in definition of macro ‘M_C2I’
 #define M_C2I(a, ...)       a ## __VA_ARGS__
...
```

**Comment by P-p-H-d** [comment]
Fixed in master.

**Comment by diraimondo** [comment]
A const-related issue:
```
#include "m-concurrent.h"
#include "m-dict.h"
#include "m-string.h"
#include "m-tuple.h"

DICT_DEF2(string_pool, string_t, string_t)
#define STRING_POOL_OPLIST                                                     \
    DICT_OPLIST(string_pool, STRING_OPLIST, STRING_OPLIST)
#define M_OPL_string_pool_t() STRING_POOL_OPLIST

CONCURRENT_DEF(string_pool_ts, string_pool_t, STRING_POOL_OPLIST)
#define STRING_POOL_TS_OPLIST                                                  \
    CONCURRENT_OPLIST(string_pool_ts, STRING_POOL_OPLIST)
#define M_OPL_string_pool_ts_t() STRING_POOL_TS_OPLIST

TUPLE_DEF2(my_tuple, (pool, string_pool_ts_t))
#define MY_TUPLE_OPLIST TUPLE_OPLIST(my_tuple, STRING_POOL_TS_OPLIST)
#define M_OPL_my_tuple_t() MY_TUPLE_OPLIST

int main() {
    M_LET(pool, string_pool_ts_t)
    M_LET(tuple, my_tuple_t) {
        //
    }
}
```

**Comment by P-p-H-d** [comment]
I was expecting this one. :)
I think I will need to do something ugly to fix it (like for buffer). :(

**Comment by P-p-H-d** [comment]
Fixed in master.

**Comment by P-p-H-d** [comment]
Doc has been committed. So far, I think everything has been done for this evolution.
