### ISSUE TITLE
How embed an __uint128_t?

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#38]
I would use as element in a container an "almost" native type `__uint128_t` (from `inttypes.h`). For lack of knowledge on the OPLIST topic I was not able to define a proper one.

Here the example:
```
#include <inttypes.h>
#include <m-tuple.h>

#define uint128_t __uint128_t
// first attempt:
// #define M_OPL_uint128_t() M_DEFAULT_OPLIST

// second attempt:
#define M_OPL_uint128_t()                                                      \
    (INIT(M_INIT_DEFAULT), INIT_SET(M_SET_DEFAULT), SET(M_SET_DEFAULT),        \
     CLEAR(M_NOTHING_DEFAULT))

TUPLE_DEF2(my_tuple, (x, int), (y, uint128_t))
#define M_OPL_my_tuple_t()                                                     \
    TUPLE_OPLIST(my_tuple, M_DEFAULT_OPLIST, M_OPL_uint128_t())

int main() {
    M_LET(t, my_tuple_t) {}
}
```

**Comment by P-p-H-d** [comment]
Your code is nearly right. The oplist definition is ok. The error is somewhere else. You should use :
`typedef __uint128_t uint128_t;`
instead of
`#define uint128_t __uint128_t`

The macros M_OPL_name() only works with types defines with typedef (well, to be exact with types that are expanded by the preprocessor as single token type).

What happens is that in TUPLE_DEF2(my_tuple, (x, int), (y, uint128_t)),
uint128_t was replaced by  __uint128_t, before M*LIB is able to test if the oplist exists.
So it tests for the existence of the macro M_OPL___uint128_t() instead of  M_OPL_uint128_t().
Since such macro doesn't exist, it uses the standard type oplist which is not compatible with
__uint128_t (in C11, it is compatible in C99).

**Comment by diraimondo** [comment]
Ok, thanks. The use of `#define` to create new type is an old bad habit...
