### ISSUE TITLE
zero-length bit field must be unnamed when using M_IPTR OPS without 

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#52]
If i don't provide this two OP functions, I get `zero-length bit field must be unnamed` error:
SET(type_set M_IPTR)
INIT_SET(type_init_set M_IPTR)

Is that an expected behavior? I thought there would be some kind of valid default OPS for these.

**Comment by P-p-H-d** [comment]
Could you give a little bit more context on the error message?

As far as I can see, you are raising a static assertion failure detected by M*LIB in C99 mode, but I don't know which one. Something like this is reported by clang/gcc/cl in similar cases:

` error: named bit-field 'M_LIB_NOT_A_DEFAULT_TYPE' has zero width`

Or you can also build in C11 mode to get a more verbose error message.

**Comment by vladipus** [comment]
I see... So the errors can be vague actually? I'm now switched to c11 mode. Will provide more info as I go. Thank you.

**Comment by P-p-H-d** [comment]
This is a language limitation. The list of internal errors that are detected are:

* M\_LIB\_NOT\_AN\_OPLIST: something has been given (directly or indirectly) and it doesn't reduce as a proper oplist. You need to give an oplist for this definition.
* M\_LIB\_ERROR(ARGUMENT\_OF\_\*\_OPLIST\_IS\_NOT\_AN\_OPLIST, name, oplist): sub error of the previous error one, identying the root cause. The error is in the oplist construction of the given macro. You need to give an oplist for this oplist construction.
* M\_LIB\_MISSING\_METHOD: a required operator doesn't define any method in the given oplist. You need to complete the oplist with the missing method.
* M\_LIB\_TYPE\_MISTMACH: the given oplist and the type do not match each other. You need to give the right oplist for this type.
* M\_LIB\_NOT\_A\_DEFAULT\_TYPE: The oplist M\_DEFAULT\_OPLIST (directly or indireclty) has been used with the given type, but the given type is not a default type. You need to give the right oplist for this type.
