### ISSUE TITLE
Enums support by the default OPLIST

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#58]
```c
typedef enum GTStatus
{
    GT_SUCCESS = 0,
    GT_LEGAL_NOOP = 1,
    GT_NULL_ARGUMENT = -1,
    GT_INVALID_ARGUMENT = -2,
    GT_NOT_FOUND = -3,
    GT_INVALID_OPERATION = -4,
    GT_OUT_OF_LIMIT = -5,
    GT_NO_MEMORY = -6,
    GT_FATAL_ERROR = -7
} GTStatus;

DEQUE_DEF(GTStatuses, GTStatus, M_OPEXTEND(M_DEFAULT_OPLIST, TYPE(GTStatus)))
```

Under Clang 9 there is an invalid OPLIST static assert. Under Clang 10 it is `Assigning to 'GTStatus' from incompatible type 'int'`

Maybe a special M_ENUM_OPLIST would solve the problem?

**Comment by vladipus** [comment]
This can be fixed with the following code:
```c
static inline void GTStatus_init(GTStatus *status) { *status = GT_SUCCESS; }

DEQUE_DEF(GTStatuses, GTStatus,
          M_OPEXTEND(M_DEFAULT_OPLIST, TYPE(GTStatus),
                     INIT(GTStatus_init M_IPTR)))
```

**Comment by P-p-H-d** [comment]
I cannot reproduce the issue (invalid oplist) with clang9. 
I can reproduce the issue (invalid assign) with clang10, but only in C++ mode (there is no such warning in C mode for me).

The solution you found is the right one. A special M_ENUM_OPLIST macro cannot be written since the initial value to set in the enum is unkown.

However, I have plan to create a ENUM_DEF (or something like that) to encapsulate the enum creation within a M\_*LIB macro in the future:
* to solve the issue you found,
* to have nice serialize functions in JSON (the enumerate string is output in the JSON instead of its value).

**Comment by vladipus** [comment]
Can that `M_ENUM_OPLIST` macro be specialized with some kind of default value argument perhaps? Something like `M_ENUM_OPLIST(enum_name, DEFAULT_ENUM_VALUE)`?
I think that some kind of documentation paragraph on that one would clear things up.

**Comment by P-p-H-d** [comment]
This is on progress.
I have some issues to solve on supporting basic  I/O with the enum.

**Comment by vladipus** [comment]
Can I help you with that somehow?

**Comment by P-p-H-d** [comment]
I don't know

I have to find tricks to return boolean within a macro while casting an enum from a long long read from a FILE.
For example, how to write the macro so that it sets *xptr to the enumerate while returning a boolean indicating its success.
`#define M_ENUM_IN_STR(oplist, xptr, f)      
`
You don't know the exact type of the enum before.

I have found a way for IN\_STR. I have yet to find another one for PARSE\_STR

**Comment by vladipus** [comment]
Unfortunately, as far as I know, there is no portable way to return values from a macro. Only GCC and Clang supports that, but not MSVC. I had to use an additional function for that exact case. Maybe a TLS global variable would do for you though?

**Comment by P-p-H-d** [comment]
Yes, a TLS global variable would work. But I am not fond of such a way.
I found a way for PARSE_STR too. I have to do some testing and I'll publish it.

**Comment by P-p-H-d** [comment]
M_ENUM_OPLIST is available in master.

**Comment by vladipus** [comment]
Checking this out. Please, wait. I will close all the issues once tested, I just have to refactor my code a bit. =)

**Comment by vladipus** [comment]
This is now tested to work (compile).
