### ISSUE TITLE
Shared pointer safety.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#69]
Wouldn't it be safer if the shared pointer's `_clear` method receive a *pointer to pointer*, that is `name_t*` instead of just `name_t` and also clear itself to `NULL` after clearing?

**Comment by P-p-H-d** [comment]
It is for intrusive shared pointer since shared pointer does it, right?

There is indeed some standards that say to set your pointer to NULL after freeing then.
However, the intrusive shared pointer interface tries to be as pointer-like as possible (contrary to the shared pointer),
so it it is not possible to do it like this with the current interface.
A new function can be added that do it however.

**Comment by vladipus** [comment]
Why can't a user do something like this in their code `name_clear(&ptr)`  ?

**Comment by P-p-H-d** [comment]
It can, but this is not enough important to change the prototype of the_clear function (API compatibility).
A new function can be added.

**Comment by vladipus** [comment]
I see, well, perhaps a `_clear_s` would do?

**Comment by P-p-H-d** [comment]
Taken into account in master as _clear_ptr
