### ISSUE TITLE
Increasing or decreasing priorities in priority queue

### ISSUE THREAD

**Issue by Zarzwick** [P-p-H-d/mlib#75]
(Hello !) In the priority queue data type, the `update_further` function seems strange, to me. Since I assume from the code that it is meant to decrease the priority (increase the value), imho the assert is reversed (it should check that xold < xnew). I could be mistaken but I needed the opposite function (increase_priority) and it worked very fine with the exact same assert.

I have this function available in a fork, if needed (wasn't sure about your contributing policy). I can add the fix of the assert (if a fix it is) as well and tag the issue. Also I'd like to say, as a non-native english speaker I couldn't determine if update_further was meant to increase or decrease the priority, since the "further" is slightly ambiguous.

**Comment by P-p-H-d** [comment]
Hello,

 You are right. The method _update_further is broken. The assert is in the wrong decision. Hopefully, it wasn't documented...

 The function doesn't work to increase the priority (decrease the value) since we need to move the data in the opposite direction in this case:
* if the priority is increased, we need to move the data from children to the parent until it is in the correct position.
* if the priority is decreased we need to move the data from the parent to the children until it is in the correct position.

 I have updated master with a (new) function for a priority queue which is simply '_update' which will update the data in the correct direction in all cases. _update_further is deprecated and will be removed shortly (currently it is only an alias to _update).

Thank you for your report.

**Comment by Zarzwick** [comment]
That solves both problems at once, indeed (marking as closed). Thank you for your reactivity (and for the great lib) :)
