### ISSUE TITLE
RB-tree _it_from on root node

### ISSUE THREAD

**Issue by xtreme8000** [P-p-H-d/mlib#93]
When using `_it_from` on a RB-tree with `data` equal to the root node, `it->cpt` is left at 0, which e.g. results in `_ref` throwing an assert and `_end_p` to be true. The issue [occurs when comparing the current node](https://github.com/P-p-H-d/mlib/blob/master/m-rbtree.h#L578) in the first while-iteration. A simple fix would be to set `it->cpt` to at least 1 there.

On another note: sometimes I observed `_it_from`returning a node greater than the `data` node, however I'm not sure yet how this happens (and might be my fault?).

**Comment by P-p-H-d** [comment]
Thank you for your bug report.
The issue should be fixed in the master branch.

For the other note, I have updated the definition of the returned iterator by _it_from the greatest element of the 'tree' lower of equal than 'data' to the lowest element of the 'tree' greater or equal than 'data'. It should be more logical and intuitive.
